#!/usr/bin/env bash

description() {
    echo "configure fish shell"
}

dependencies() {
    echo ""
}

main() {
    fish -c 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher'
    fish -c 'fisher install jethrokuan/z'
    fish -c 'fisher install edc/bass'
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi


