#!/usr/bin/env bash

description() {
    echo "link home bin"
}

dependencies() {
    echo ""
}

main() {
    set -eu

    DOTS_ROOT=$(git rev-parse --show-toplevel)

    ln -fs $DOTS_ROOT/assets/bin $HOME/bin

    echo "don't forget to add \"$HOME/bin\" to your path"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi
