#!/usr/bin/env bash

description() {
    echo 'set up $SSH_AUTH_SOCK'
}

dependencies() {
    echo "profile-home"
}

main() {
    set -eux
    DOTS_ROOT=$(git rev-parse --show-toplevel)
    cp -f $DOTS_ROOT/configs/home-profile.d/ssh-agent $HOME/.profile.d/ssh-agent
    mkdir -p $HOME/.config/systemd/user
    cp -f $DOTS_ROOT/configs/user-units/ssh-agent.service $HOME/.config/systemd/user/ssh-agent.service
    systemctl --user enable ssh-agent
    systemctl --user start ssh-agent
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi