#!/usr/bin/env bash

description() {
    echo 'set up $SSH_AUTH_SOCK'
}

dependencies() {
    echo ""
}

main() {
    set -eux
    DOTS_ROOT=$(git rev-parse --show-toplevel)
    mkdir -p $HOME/.config/environment.d
    ln -f $DOTS_ROOT/configs/environment.d/ssh-agent.conf $HOME/.config/environment.d/ssh-agent.conf
    mkdir -p $HOME/.config/systemd/user
    ln -f $DOTS_ROOT/configs/user-units/ssh-agent.service $HOME/.config/systemd/user/ssh-agent.service
    systemctl --user enable ssh-agent
    systemctl --user start ssh-agent
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi
